### ISSUE TITLE
Introducing TechSpecs API

### ISSUE THREAD

**Issue by realtechspecs** [azharimm/phone-specs-api#9]
Hi everyone,

We've launched an API that provides the easiest way for you to get the official technical specifications of every consumer electronics product in the world, just in a few seconds. Our database is updated on a daily basis so you always have access to the latest specs. 

Our API is ready and currently in private beta. 

Read the docs here https://techspecs.readme.io

Get early access here https://developer.techspecs.io/

**Comment by azharimm** [comment]
please don't submit anything other than issues. thanks!

**Comment by congshengwu** [comment]
Hi @azharimm, thanks for this open source project.

I am curious about the user _realtechspecs_, I see the same content more than twice and you closed it. 

Is it your product company, or just an AD from the unexpected third-pary organization?

**Comment by azharimm** [comment]
Hi, it's an ad and he's spamming couple times. you should probably check their project if you are curious. it's a nice project.
